spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxxx:3306/xx?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&functionsNeverReturnBlobs=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
    username: xx
    password: xx
  redis:
    database: 7
    host: xx
    port: 6379
    password: xx
    jedis:
      pool:
        max-active: 16
        max-wait: -1
        max-idle: 16
        min-idle: 0
    timeout: 10000
wjj:
  worker:
    easyfood:
      notifyUrl: https://api.day.app/xx/{title}/{value}
      addressKeyWord: 你的地址关键词关键词对应叮咚买菜中的 "门牌号" 模糊搜索
      userId: 用户ID通关抓包获取
      userToken: 用户token通过抓包获取

